name : python ci
on:
  push :
  branches :
    -main

    job:
      build:
        runs-on: ubuntu-latest
        steps:
          -name : checkout code
          uses :actions/checkout@v2
          -name : setup python
          uses : actions/setup-python@v2
          with version : 3.8

      -name : install dependencies
        run : /
        pip install -r requirements .txt
        
        -name : run application
        run : python app.py

       
